name: Publish llama-index to PyPI / GitHub

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

env:
  POETRY_VERSION: "1.8.3"
  PYTHON_VERSION: "3.11"

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    if: github.repository == 'run-llama/llama_deploy'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@7100bd02517e9f82452e6247849042f6c74dde04 # v2.0
        with:
          python_version: ${{ env.PYTHON_VERSION }}
          pypi_token: ${{ secrets.LLAMA_AGENTS_PYPI_TOKEN }}
          poetry_install_options: "--with dev"

      - name: Create GitHub Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
        with:
          artifacts: "dist/*"
          generateReleaseNotes: true
